# Generated by Django 5.2.7 on 2025-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='breakfast_day4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='breakfast_day5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='breakfast_day6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='breakfast_day7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='lunch_day4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='lunch_day5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='lunch_day6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='lunch_day7',
            field=models.BooleanField(default=False),
        ),
    ]
