# Generated by Django 5.2.7 on 2025-10-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
