# Generated by Django 5.2.7 on 2025-10-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participant_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('checkin_admin', 'Check-in Admin')], default='checkin_admin', max_length=20),
        ),
    ]
