# Generated by Django 5.2.7 on 2025-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_adminactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='qr_code_data',
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('free', 'Free Access')], default='unpaid', max_length=10),
        ),
    ]
