# Generated by Django 5.2.7 on 2025-11-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_remove_participant_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='participant',
            name='free_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
