# Generated by Django 5.2.7 on 2025-11-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_remove_participant_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day1',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day2',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day3',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day4',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day5',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day6',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='breakfast_day7',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='free_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_present',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day1',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day2',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day3',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day4',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day5',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day6',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lunch_day7',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nationality',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['paid', 'free_access'], name='participant_paid_2b1c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['nationality', 'paid'], name='participant_nationa_ab9316_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_present'], name='participant_is_pres_6000fe_idx'),
        ),
    ]
